import {
  PlanParseError,
  type ParsedPlan,
  type PlanNode,
  type RawExplainRoot,
  type RawPlanNode,
} from './types.js';

/**
 * Rounding inside Postgres means a parent's reported time can come out very
 * slightly below the sum of its children. Anything under this many
 * milliseconds of apparent negative time is treated as noise and clamped.
 * Anything above it is worth surfacing, because it means we misread the shape.
 */
const NEGATIVE_TIME_TOLERANCE_MS = 1;

/** Guard against a pathological plan locking up the browser. */
const MAX_NODES = 5000;

interface WalkContext {
  nextId: number;
  nodes: PlanNode[];
  warnings: string[];
}

export function parsePlan(input: string): ParsedPlan {
  const trimmed = input.trim();

  if (!trimmed) {
    throw new PlanParseError(
      'Nothing to read.',
      'Paste the output of EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON).',
    );
  }

  if (looksLikeTextFormat(trimmed)) {
    throw new PlanParseError(
      'This looks like the default text output, not JSON.',
      'Re-run the query as EXPLAIN (ANALYZE, BUFFERS, FORMAT JSON) and paste that instead. Text format is not supported yet.',
    );
  }

  let json: unknown;
  try {
    json = JSON.parse(trimmed);
  } catch {
    throw new PlanParseError(
      'That is not valid JSON.',
      'Copy the whole result, including the outer square brackets. Some clients truncate long output or wrap it in quotes.',
    );
  }

  const root = extractRoot(json);

  if (!root.Plan) {
    throw new PlanParseError(
      'No plan found in that JSON.',
      'The output should contain a "Plan" key at the top level. That comes from FORMAT JSON.',
    );
  }

  const ctx: WalkContext = { nextId: 0, nodes: [], warnings: [] };
  const tree = walk(root.Plan, 0, null, null, ctx);

  const totalExclusive = ctx.nodes.reduce((sum, n) => sum + (n.exclusiveMs ?? 0), 0);

  return {
    root: tree,
    nodes: ctx.nodes,
    timed: tree.timed,
    planningTimeMs: numberOrNull(root['Planning Time']),
    executionTimeMs: numberOrNull(root['Execution Time']),
    totalExclusiveMs: totalExclusive,
    triggers: Array.isArray(root.Triggers) ? root.Triggers : [],
    queryText: typeof root['Query Text'] === 'string' ? root['Query Text'] : null,
    settings: isRecord(root.Settings)
      ? (root.Settings as Record<string, string>)
      : null,
    warnings: ctx.warnings,
  };
}

/**
 * EXPLAIN JSON is normally an array with one element, but pgAdmin and some
 * drivers hand back the object directly, and a few wrap it again.
 */
function extractRoot(json: unknown): RawExplainRoot {
  let candidate: unknown = json;

  for (let depth = 0; depth < 3; depth += 1) {
    if (Array.isArray(candidate)) {
      if (candidate.length === 0) {
        throw new PlanParseError(
          'That JSON array is empty.',
          'Make sure you copied the full result, not just the brackets.',
        );
      }
      candidate = candidate[0];
      continue;
    }
    break;
  }

  if (!isRecord(candidate)) {
    throw new PlanParseError(
      'The JSON did not contain a plan object.',
      'Expected an object with a "Plan" key. Check that you pasted the query result and not the query.',
    );
  }

  return candidate as RawExplainRoot;
}

function walk(
  raw: RawPlanNode,
  depth: number,
  parent: PlanNode | null,
  relationship: string | null,
  ctx: WalkContext,
): PlanNode {
  if (ctx.nextId >= MAX_NODES) {
    throw new PlanParseError(
      `This plan has more than ${MAX_NODES} nodes.`,
      'Plans that large are usually generated by a query over many partitions. Support for collapsing them is on the roadmap.',
    );
  }

  const id = ctx.nextId;
  ctx.nextId += 1;

  const node: PlanNode = {
    id,
    depth,
    relationship,
    raw,
    children: [],
    parent,
    timed: raw['Actual Total Time'] !== undefined,
    loops: positiveOr(raw['Actual Loops'], 1),
    inclusiveMs: null,
    exclusiveMs: null,
    actualRows: null,
    plannedRows: 0,
    estimateFactor: null,
    overEstimated: false,
    label: describe(raw),
    target: targetOf(raw),
  };

  ctx.nodes.push(node);

  for (const child of collectChildren(raw)) {
    node.children.push(walk(child.raw, depth + 1, node, child.relationship, ctx));
  }

  computeTiming(node, ctx);
  computeRows(node);

  return node;
}

interface ChildRef {
  raw: RawPlanNode;
  relationship: string | null;
}

/**
 * Children always live under "Plans". CTEs, InitPlans and SubPlans are in
 * there too, distinguished by "Parent Relationship" rather than by a separate
 * key, which is easy to miss.
 */
function collectChildren(raw: RawPlanNode): ChildRef[] {
  if (!Array.isArray(raw.Plans)) return [];

  return raw.Plans.filter(isRecord).map((child) => ({
    raw: child as RawPlanNode,
    relationship:
      typeof (child as RawPlanNode)['Parent Relationship'] === 'string'
        ? ((child as RawPlanNode)['Parent Relationship'] as string)
        : null,
  }));
}

/**
 * Postgres reports Actual Total Time as an average per loop, inclusive of
 * children. Real elapsed time is that average multiplied by the loop count.
 * Own work is what remains after the children are subtracted.
 *
 * Getting the loop multiplication wrong is the single most common bug in
 * tools like this: on a nested loop running 50,000 times, the reported 0.02ms
 * is really a full second.
 */
function computeTiming(node: PlanNode, ctx: WalkContext): void {
  if (!node.timed) {
    node.timed = node.children.some((c) => c.timed);
    if (!node.timed) return;
  }

  const perLoop = numberOr(node.raw['Actual Total Time'], 0);
  const inclusive = perLoop * node.loops;
  const childSum = node.children.reduce((sum, c) => sum + (c.inclusiveMs ?? 0), 0);
  const exclusive = inclusive - childSum;

  node.inclusiveMs = inclusive;

  if (exclusive < -NEGATIVE_TIME_TOLERANCE_MS) {
    ctx.warnings.push(
      `Node ${node.id} (${node.label}) reports less time than its children. ` +
        'This usually means a parallel plan where worker time is counted twice.',
    );
    node.exclusiveMs = 0;
  } else {
    node.exclusiveMs = Math.max(0, exclusive);
  }
}

function computeRows(node: PlanNode): void {
  const loops = node.loops;
  node.plannedRows = numberOr(node.raw['Plan Rows'], 0) * loops;

  if (node.raw['Actual Rows'] === undefined) {
    node.actualRows = null;
    return;
  }

  node.actualRows = numberOr(node.raw['Actual Rows'], 0) * loops;

  if (node.plannedRows > 0 && node.actualRows > 0) {
    const over = node.plannedRows > node.actualRows;
    node.overEstimated = over;
    node.estimateFactor = over
      ? node.plannedRows / node.actualRows
      : node.actualRows / node.plannedRows;
  } else if (node.plannedRows > 0 && node.actualRows === 0) {
    node.overEstimated = true;
    node.estimateFactor = node.plannedRows;
  }
}

function describe(raw: RawPlanNode): string {
  const type = raw['Node Type'] ?? 'Node';
  let label = type;

  if (type === 'Aggregate' && typeof raw.Strategy === 'string') {
    label = raw.Strategy === 'Plain' ? 'Aggregate' : `${raw.Strategy} Aggregate`;
  }

  if (type === 'ModifyTable' && typeof raw.Operation === 'string') {
    label = raw.Operation;
  }

  if (raw['Parallel Aware']) label = `Parallel ${label}`;

  if (typeof raw['Join Type'] === 'string' && type.includes('Join')) {
    if (raw['Join Type'] !== 'Inner') label = `${label} (${raw['Join Type']})`;
  }

  if (
    typeof raw['Scan Direction'] === 'string' &&
    raw['Scan Direction'] === 'Backward'
  ) {
    label = `${label} Backward`;
  }

  return label;
}

function targetOf(raw: RawPlanNode): string | null {
  const relation = raw['Relation Name'];
  const index = raw['Index Name'];
  const alias = raw.Alias;

  if (typeof relation === 'string') {
    const aliasPart =
      typeof alias === 'string' && alias !== relation ? ` ${alias}` : '';
    const indexPart = typeof index === 'string' ? ` using ${index}` : '';
    return `on ${relation}${aliasPart}${indexPart}`;
  }

  if (typeof index === 'string') return `using ${index}`;
  if (typeof raw['CTE Name'] === 'string') return `cte ${raw['CTE Name']}`;
  if (typeof raw['Function Name'] === 'string') return `${raw['Function Name']}()`;
  if (typeof raw['Subplan Name'] === 'string') return raw['Subplan Name'];

  return null;
}

/**
 * The commonest first-run mistake is pasting the default text format. Catch it
 * before the JSON parser produces an unhelpful message about position 0.
 */
function looksLikeTextFormat(text: string): boolean {
  if (text.startsWith('[') || text.startsWith('{')) return false;
  return (
    /\(cost=\d/.test(text) ||
    /^\s*(QUERY PLAN|-{3,})/m.test(text) ||
    /->\s{2}\w/.test(text)
  );
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function numberOr(value: unknown, fallback: number): number {
  return typeof value === 'number' && Number.isFinite(value) ? value : fallback;
}

function numberOrNull(value: unknown): number | null {
  return typeof value === 'number' && Number.isFinite(value) ? value : null;
}

function positiveOr(value: unknown, fallback: number): number {
  const n = numberOr(value, fallback);
  return n > 0 ? n : fallback;
}
